// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqXrk1psaG9xdn9Oai_6cWwxyahNP6U6Q',
    appId: '1:785270247289:web:4400c6e5eee5ae3213e9a8',
    messagingSenderId: '785270247289',
    projectId: 'mopro-d865d',
    authDomain: 'mopro-d865d.firebaseapp.com',
    storageBucket: 'mopro-d865d.firebasestorage.app',
    measurementId: 'G-R3L99R41VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEzfSz2cgG0OkfiuLskmEQJdKFAmkxfW0',
    appId: '1:785270247289:android:833969d1d4fefa4713e9a8',
    messagingSenderId: '785270247289',
    projectId: 'mopro-d865d',
    storageBucket: 'mopro-d865d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYLJgnj7V9lqlh4-6XDrM48volYBF474',
    appId: '1:785270247289:ios:bb607b1ba4fe916e13e9a8',
    messagingSenderId: '785270247289',
    projectId: 'mopro-d865d',
    storageBucket: 'mopro-d865d.firebasestorage.app',
    iosClientId: '785270247289-uc73gfth9bevepin527e9sfpctldvjpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.reportme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpYLJgnj7V9lqlh4-6XDrM48volYBF474',
    appId: '1:785270247289:ios:bb607b1ba4fe916e13e9a8',
    messagingSenderId: '785270247289',
    projectId: 'mopro-d865d',
    storageBucket: 'mopro-d865d.firebasestorage.app',
    iosClientId: '785270247289-uc73gfth9bevepin527e9sfpctldvjpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.reportme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqXrk1psaG9xdn9Oai_6cWwxyahNP6U6Q',
    appId: '1:785270247289:web:da6429234959b05113e9a8',
    messagingSenderId: '785270247289',
    projectId: 'mopro-d865d',
    authDomain: 'mopro-d865d.firebaseapp.com',
    storageBucket: 'mopro-d865d.firebasestorage.app',
    measurementId: 'G-WFTFF9DS6B',
  );
}
